In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("experiment_data.csv")
df

,Dataset,Split,Shape,Components,Duplicated sets,Set copies,Max set size difference,Max element size difference,Vacant cells,Sparsity (%),...,Total layout time (s),Total arrange time (s),Bounding box width,Bounding box height,Bounding box (cells),Blank cells,Blank orthoconvex hull cells,Average set squareness,Average set vertices,Average set straight sides
0,Tulips,BlockSets,Arbitrary_MSE,1,0,0,0,0,0,0.00,...,0.1785,1.2834,5,4,20,8,0,0.6222,6.0000,3.0000
1,Tulips,BlockSets,Arbitrary_MSP,1,0,0,0,0,0,0.00,...,60.0620,2.5516,4,3,12,0,0,0.5370,4.4444,3.5556
2,Tulips,BlockSets,Orthoconvex,1,0,0,0,0,0,0.00,...,60.2828,2.0600,3,5,15,3,0,0.5833,4.6667,3.3333
3,Tulips,BlockSets,Nabla,1,0,0,0,0,1,6.67,...,60.1936,0.4948,3,5,15,2,0,0.5370,4.2222,3.7778
4,Tulips,BlockSets,Gamma,1,0,0,0,0,0,0.00,...,60.2263,0.3745,5,4,20,8,1,0.5426,4.4444,3.5556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,LOTR,RectEuler,Arbitrary_MSP,8,21,73,10,15,0,0.00,...,677.7100,66.3037,12,12,144,54,1,0.8388,5.2553,3.1489
200,LOTR,RectEuler,Orthoconvex,8,21,73,10,15,5,3.79,...,787.6888,64.9103,12,11,132,37,6,0.8039,5.2128,3.0106
201,LOTR,RectEuler,Nabla,11,21,91,10,13,6,5.56,...,1049.3996,61.3720,9,12,108,12,2,0.8082,4.5536,3.5000
202,LOTR,RectEuler,Gamma,11,21,91,10,13,14,10.61,...,1049.4442,60.7792,12,11,132,28,6,0.7588,4.5179,3.5357
203,LOTR,RectEuler,Rectangle,9,21,76,12,18,106,50.48,...,545.6750,62.5799,14,15,210,14,1,0.5567,4.0000,4.0000

In [3]:
df_agg = (df.groupby(["Shape"])
             .mean(numeric_only=True))
df_agg

,Components,Duplicated sets,Set copies,Max set size difference,Max element size difference,Vacant cells,Sparsity (%),Total split time (s),Total layout time (s),Total arrange time (s),Bounding box width,Bounding box height,Bounding box (cells),Blank cells,Blank orthoconvex hull cells,Average set squareness,Average set vertices,Average set straight sides
Shape,,,,,,,,,,,,,,,,,,
Arbitrary_MSE,3.600000,5.257143,12.228571,4.628571,6.600000,0.000000,0.000000,2.719854,114.405926,19.465771,6.028571,6.314286,43.828571,15.428571,3.371429,0.743514,6.495946,2.481763
Arbitrary_MSP,4.233333,5.666667,15.100000,3.800000,4.700000,0.000000,0.000000,3.513790,220.217483,24.082180,5.666667,5.633333,35.900000,6.566667,0.133333,0.736683,5.360517,2.960013
Gamma,3.552632,5.868421,12.763158,4.868421,5.368421,8.342105,15.091053,2.784618,262.071279,6.575116,6.657895,6.447368,46.631579,11.026316,0.921053,0.672587,4.833561,3.323021
Nabla,3.324324,5.729730,11.891892,4.324324,5.405405,6.648649,11.171622,2.885559,241.285957,7.967232,6.243243,6.432432,43.432432,9.108108,0.945946,0.675868,5.105778,3.102016
Orthoconvex,3.000000,5.454545,10.939394,4.727273,5.636364,2.606061,3.724848,2.845648,219.088394,15.970224,5.757576,6.000000,38.606061,7.090909,0.606061,0.694230,5.515085,2.757758
Rectangle,3.032258,4.451613,11.935484,2.645161,4.000000,33.903226,45.883226,2.318823,112.856765,11.834890,7.903226,8.258065,71.870968,9.096774,0.354839,0.245352,4.000000,4.000000

In [4]:
cols = ["Total layout time (s)", "Components", "Sparsity (%)", "Bounding box (cells)", "Blank orthoconvex hull cells", "Average set squareness", "Average set vertices", "Average set straight sides"]

In [5]:
rows = []

for dataset, row in df_agg.iterrows():
    line = [dataset]

    for col in cols:
        a = row[col]
        line.extend([f"{a:.3g}"])

    rows.append(" & ".join(line) + r" \\")

print("\n".join(rows))

Arbitrary_MSE & 114 & 3.6 & 0 & 43.8 & 3.37 & 0.744 & 6.5 & 2.48 \\
Arbitrary_MSP & 220 & 4.23 & 0 & 35.9 & 0.133 & 0.737 & 5.36 & 2.96 \\
Gamma & 262 & 3.55 & 15.1 & 46.6 & 0.921 & 0.673 & 4.83 & 3.32 \\
Nabla & 241 & 3.32 & 11.2 & 43.4 & 0.946 & 0.676 & 5.11 & 3.1 \\
Orthoconvex & 219 & 3 & 3.72 & 38.6 & 0.606 & 0.694 & 5.52 & 2.76 \\
Rectangle & 113 & 3.03 & 45.9 & 71.9 & 0.355 & 0.245 & 4 & 4 \\